### ISSUE TITLE
Mutable Default Arguments

### ISSUE THREAD

**Issue by bangyen** [RojerGS/Brainetry#9]
Because the default value for `m` is a mutable type (`list`), when `E` is called multiple times, the output of latter runs is incorrect.

**Comment by rodrigogiraoserrao** [comment]
You are right, when I used the default `m = [0]` I thought it wouldn't matter because the interpreter would only be run once, but seeing your draft for the tests in #8 it becomes obvious I'll need to run the interpreter several times. Thanks for this.
